on: [push, pull_request]
name: Build
jobs:
  buildmin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.16.x
        check-latest: true
    - name: Build
      run: go build
  buildmax:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
        cache: true
    - name: Build
      run: go build
